# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'basisProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for basisProject
pod 'SDWebImage','3.8.2'
pod 'MJExtension'
pod 'Masonry','~>1.0.2'
pod 'ACAlertController','1.0.0'
pod 'TZImagePickerController','1.9.8'
pod 'MWPhotoBrowser','2.1.1'


end
